# Generated by Django 5.0.6 on 2026-06-14 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('direction', models.CharField(choices=[('export', 'Export'), ('import', 'Import')], max_length=10)),
                ('mode', models.CharField(choices=[('fcl', 'FCL'), ('lcl', 'LCL'), ('air', 'Air cargo'), ('express', 'Express')], max_length=10)),
                ('op_status', models.CharField(choices=[('departed', 'Khởi hành'), ('docs_receiving', 'Tiếp nhận chứng từ'), ('customs', 'Khai hải quan'), ('arrived', 'Đã cập cảng')], default='departed', max_length=20)),
                ('origin', models.CharField(blank=True, max_length=120)),
                ('destination', models.CharField(blank=True, max_length=120)),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.CharField(blank=True, max_length=80)),
                ('weight', models.CharField(blank=True, max_length=80)),
                ('cbm', models.CharField(blank=True, max_length=80)),
                ('container', models.CharField(blank=True, max_length=120)),
                ('etd', models.DateField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('vessel', models.CharField(blank=True, max_length=120)),
                ('voyage', models.CharField(blank=True, max_length=80)),
                ('carrier', models.CharField(blank=True, max_length=120)),
                ('si_cutoff', models.DateTimeField(blank=True, null=True)),
                ('vgm_cutoff', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='accounts.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='VND', max_length=8)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('proof', models.FileField(blank=True, null=True, upload_to='payments/%Y/%m/')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='shipments.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(max_length=160)),
                ('action', models.CharField(max_length=200)),
                ('detail', models.CharField(blank=True, max_length=400)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('bill', 'Bill of Lading'), ('invoice', 'Commercial Invoice'), ('packing', 'Packing List'), ('co', 'Certificate of Origin'), ('contract', 'Sales contract / Proforma invoice'), ('other', 'Khác')], max_length=20)),
                ('processing_status', models.CharField(choices=[('pending', 'Chờ nộp'), ('review', 'Review'), ('revision', 'Revision'), ('completed', 'Completed')], default='pending', max_length=12)),
                ('business_status', models.CharField(choices=[('none', '--'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('released', 'Released')], default='none', max_length=12)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shipments.shipment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['doc_type', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ'), ('processing', 'Đang xử lí'), ('done', 'Hoàn thành')], default='pending', max_length=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='shipments.shipment')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
