# Generated by Django 5.0.6 on 2026-06-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenttask',
            name='actual_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
